language: bash
git:
  submodules: false

cache:
  directories:
    - ${HOME}/gcloud/

# https://docs.travis-ci.com/user/environment-variables/
env:
  global:
    - GOOGLE_CREDENTIALS=${TRAVIS_BUILD_DIR}/credentials.json
    - TRAVIS_COMMIT_SHORT=${TRAVIS_COMMIT::8}

before_install:
  - echo "setting .sh files +x permission"  
  - chmod +x travis/environment_vars.sh
  - chmod +x travis/install_gcloud.sh
  - chmod +x travis/submit.sh
  - chmod +x travis/test.sh
  
# Run for PULL REQUEST or for any commit into a master branch or a release branch

# https://docs.travis-ci.com/user/conditions-v1
# https://docs.travis-ci.com/user/conditional-builds-stages-jobs/
if: >-
  type = pull_request
  OR branch = master
  OR branch =~ ^release-

# https://docs.travis-ci.com/user/build-stages
jobs:
  include:
    - stage: build image
      script: bash travis/submit.sh
    - stage: tests
      name: running tests
      script: bash travis/test.sh

install:
  - travis/environment_vars.sh
  - travis/install_gcloud.sh

# https://docs.travis-ci.com/user/notifications/#configuring-slack-notifications
# https://docs.travis-ci.com/user/encryption-keys/#usage
notifications:
  slack: dotcms:oKpntVOdtRymXMrB2Soax5So