version: '2'
services:
  npm_test:
    image: "${IMAGE_BASE_NAME}"
    command: npm test -- dotcms-ui --watch=false --reporters=html,progress
  runnig_test:
    image: "${IMAGE_BASE_NAME}"
    command: bash -c "storage.sh"