steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/core-web-test-image:$_COMMIT_SHORT',
            '.' ]
images:
  - 'gcr.io/$PROJECT_ID/core-web-test-image:$_COMMIT_SHORT'

timeout: 1200s