name: cypress-tests
on: [ push ]
jobs:
  cypress-tests:
    name: Cypress Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test Docker
        run: docker ps -a
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          project: ./apps/dotcms-ui-e2e
          build: npm run build:prod
          env: host=demo.dotcms.com,port=80
          browser: chrome
          headless: true