name: cypress-tests
on: [ push ]
jobs:
  cypress-tests:
    name: Cypress Tests
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      DOT_CICD_BRANCH: issue-20341-trigger-cypress-tests-using-github-actions
      GITHUB_USER_TOKEN: ${{ secrets.CICD_GITHUB_TOKEN }}
      PULL_REQUEST: ${{ github.event.number }}
      DEBUG: true
    steps:
      - name: GITHUB CONTEXT
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
        if: env.DEBUG == 'true'
      - name: Get commit message
        id: get-commit-message
        uses: dotcms/get-commit-message@master
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Common Vars
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            CORE_WEB_BUILD_ID="${{ github.head_ref }}"
          else
            CORE_WEB_BUILD_ID=$(basename "${{ github.ref }}")
          fi
          COMMIT_MESSG="${{ steps.get-commit-message.outputs.commit_message }}"
          echo "COMMIT_MESSG: ${COMMIT_MESSG}"
          if [[ ${COMMIT_MESSG} =~ run-cypress ]]; then
            jobRun=true
          else
            jobRun=false
          fi
          echo "jobRun=${jobRun}" >> $GITHUB_ENV
          echo "CORE_WEB_BUILD_ID=${CORE_WEB_BUILD_ID}" >> $GITHUB_ENV
      - name: Prepare dot-cicd
        run: |
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/dotCMS/dot-cicd/${DOT_CICD_BRANCH}/seed/install-dot-cicd.sh)"
        if: env.jobRun == 'true'
      - name: Run Cypress Tests
        run: |
          ../dotcicd/library/pipeline.sh runSidecar
        if: env.jobRun == 'true'
        env:
          BUNDLE_LOCATION: core-web/apps/dotcms-ui-e2e/src/fixtures/Cypress-DB-Seed.tar.gz
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          LICENSE_KEY: ${{ secrets.DOTCMS_LICENSE }}
          # WAIT_DOTCMS_FOR: 3m
          # BUILD_ID: master ask in dot-cdci if exist, or use master instead
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test Docker
        run: docker ps -a
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          project: ./apps/dotcms-ui-e2e
          build: npm run build:prod
          wait-on: 'http://127.0.0.1:8080'
          wait-on-timeout: 120
          browser: chrome
          headless: true