name: DotCMS/core-web Tests
on:
  pull_request:
  push:
    branches:
      - master
      - release-*     
jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_USER_TOKEN }}
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ./dotcicd/test-results
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}      
      - name: Setting Node.js 10.x
        uses: actions/setup-node@v2-beta
        with:
          node-version: '10.15.3'
      - name: Installing dependencies
        run: npm install
      - name: Building Libs
        run: npm run build:libs
      - name: Building for production
        run: npm run build:prod
      - name: Running tests
        id: test-run
        run: |
          npm run test -- dotcms-ui --watch=false --reporters=html,progress
      - name: Prepare and Push to GitHub
        run: |
          chmod +x .cicd/github.sh && source .cicd/github.sh
          persistResults
      # - name: Slack Notification
      #   uses: rtCamp/action-slack-notify@master
      #   env:
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      #     SLACK_USERNAME: core-web
      #     SLACK_ICON: https://avatars.slack-edge.com/2020-09-21/1362682893351_5b474f175640cf5f5912_72.png
      #     SLACK_COLOR: '#3278BD'          
      - name: Printing Logs
        run: |
          source .cicd/github.sh
          logResults